[phases.setup]
nixPkgs = ["libGL", "glib", "xorg.libX11", "xorg.libXext", "xorg.libSM", "xorg.libICE"]

[phases.install]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[phases.start]
cmd = "gunicorn app:app --bind 0.0.0.0:8080"
